const text: any = {
  UA: {
    Clear: 'Очистити',
    Save: 'Зберегти',
    Title: 'Назва',
    UrgentTask: 'Термінова задача',
    LastUpdate: 'Оновлене',
    Yesterday: 'Вчора',
    Cancel: 'Скасувати',
    Delete: 'Видалити',
    DeleteTask: 'Видалити задачу',
    DoYouWantToDeleteTask: 'Ви хочете видалити задачу',
    Edit: 'Редагувати',
    Back: 'Назад',
    Task: 'Задача',
    Urgent: 'Термінова',
    Regular: 'Звичайна',
    Author: 'Автор',
    Created: 'Створена',
    UpdateFolder: 'Редагувати папку',
    CreateFolder: 'Створити папку',
    Create: 'Створити',
    DeleteFolder: 'Видалити папку',
    ChooseColor: 'Оберіть колір',
    ChooseIcon: 'Оберіть іконку',
    DoYouWantToDeleteFolder: 'Ви хочете видалити папку',
  },
}

export default text
