const text: any = {
  UA: {
    Login: 'Вхід',
    Registration: 'Реєстрація',
    Clear: 'Очистити',
    Save: 'Зберегти',
    title: 'назва',
    UrgentTask: 'Термінова задача',
    LastUpdate: 'Оновлене',
    Yesterday: 'Вчора',
    Cancel: 'Скасувати',
    Delete: 'Видалити',
    DeleteTask: 'Видалити задачу',
    DoYouWantToDeleteTask: 'Ви хочете видалити задачу',
    Edit: 'Редагувати',
    Back: 'Назад',
    Task: 'Задача',
    Urgent: 'Термінова',
    Regular: 'Звичайна',
    Author: 'Автор',
    Created: 'Створена',
    UpdateFolder: 'Редагувати папку',
    CreateFolder: 'Створити папку',
    Create: 'Створити',
    DeleteFolder: 'Видалити папку',
    ChooseColor: 'Оберіть колір',
    ChooseIcon: 'Оберіть іконку',
    DoYouWantToDeleteFolder: 'Ви хочете видалити папку',
    CreateFamily: "Створити сім'ю",
    EnterFamily: "Доєднатись до сім'ї",
    FamilyFolders: 'Сімейні папки',
    EditAccount: 'Редагування профілю',
    CreateAccount: 'Створення профілю',
    name: "ім'я",
    password: 'пароль',
    Settings: 'Налаштування',
    LogOut: 'Вийти з аккаунту',
    YourFamilies: "Ваші сім'ї",
    FamilyPassword: 'Пароль',
    FamilyUsers: 'Учасники',
    Enter: 'Доєднатись',
    CreateTask: 'Створити задачу',
    UpdateTask: 'Редагувати задачу',
    NoTasksYet: 'Поки нема жодної задачі',
  },
}

export default text
